# Server
server.port: 8090
server.error:
  include-binding-errors: always
  include-message: always

# Hibernate
spring.jpa:
  # Run scripts in data.sql after Hibernate is initialized
  defer-datasource-initialization: true
  properties.hibernate:
    hbm2ddl.auto: update
    show_sql: true
    use_sql_comments: true
    format_sql: true

# Uncomment to debug Swagger and Swagger UI issues
# logging.level.springfox.documentation: DEBUG
